### ISSUE TITLE
Large amount of items dropping resulting in instant bans

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/AFK-Player-GC#11]
So multiple people confirmed that if you pop filled chests/double chests, you receive a ban right away. The amount of dropped entities seems to be the reason.

**Comment by ProgrammerDan** [comment]
We could simply zero out the DROPPED_ITEM line in the config. I'm a little confused, because tl;dr item stacking, popping a chest should be at most 54 new DROPPED_ITEM entities.

**Comment by Maxopoly** [comment]
It confused me as well, but multiple people told me completly independent from each other.

**Comment by ProgrammerDan** [comment]
Oh, but of course. The issue wasn't the popped chest. This is a false correlation. Dollars to donuts its because they are in a chest vault, surrounded with factories and other auto-machines. 

Email me the names of the people who PM'd you, just got a dump, I'll be filtering and sanitizing in a moment but I can prioritize these sorts of "odd" reports.

**Comment by Maxopoly** [comment]
Sent

**Comment by ProgrammerDan** [comment]
Just a note: never did confirm this; standing by my theory as a number of folks during that event were kickbanned due to vast numbers of chests (1k+) in their immediate vicinity. Simply coincidence that it occurred right after popping the chest.
